### ISSUE TITLE
Feature request: tint2-style "multi_desktop" split taskbar

### ISSUE THREAD

**Issue by lstrtstr** [LBCrion/sfwbar#111]
Are there any plans for a tint2-style "multi_desktop" option for the taskbar widget?

https://gitlab.com/o9000/tint2/blob/master/doc/tint2.md#taskbar-pager

If set in the tint2 configuration, the taskbar is split into one per workspace, so if you have three workspaces, there's a taskbar on the left for the windows on the first workspace, one in the middle for those on the second workspace, and one on the right for the third workspace.
You can drag and drop tasks between workspaces and click on an empty taskbar to switch to that workspace.

It's a different approach to the "pager" feature, and it's _really_ convenient (and unique?). It's one of the main reasons I'm still on X11.

Any hopes for this getting implemented in sfwbar, or is this out of scope?

**Comment by LBCrion** [comment]
This is certainly not out of scope. I remember seeing this when I mocked up the tint2 look-alike config. The main reason I haven't implemented it so far, is that no-one asked for it until now :)

That said, there are some limitations / peculiarities we'll need to deal with here:
1. Wayland protocols don't expose workspaces for now, so we'll have the same caveats as for the pager and workspace filtering - this will only work with sway and hyprland until the relevant protocols are merged and implemented by compositors.
2. Taskbars in sfwbar can be multiline and this can result in some visual peculiarities. I don't think this should be a major problem.
3. Taskbar items will not necessarily be the same width for all workspaces. Due to #2, we'll need to implement this mode as a main taskbar containing sub-taskbars for each workspace (realistically this will probably leverage taskbar groups code used for win10 look-alike config). Since each sub-taskbar will be it's own grid, the items will only have homogeneous width within each sub-taskbar.

**Comment by LBCrion** [comment]
Just to update you on this, now that 1.0beta13 is out, this is the next item on my list to work on.

**Comment by lstrtstr** [comment]
Thanks for the update, and thanks for considering this feature! I really appreciate it.
As far as I'm concerned, take your time, though! I'm still waiting for ext-workspace to be merged in Wayland upstream and then implemented in labwc... 😄

**Comment by LBCrion** [comment]
I merged support for this functionality into the latest git version. Or at least my interpretation of it. The below screenshot shows how it looks. Each workspace has it's name followed by buttons for all windows on this workspace. Dragging windows into another workspace moves them to that workspace (you can drag either into a workspace label or any window button on that workspace). 

If you want to play around with it, you can enable it using "group = pager" in the taskbar definition. Each taskbar group (workspace) has a CSS node "taskbar_pager_normal" or "taskbar_pager_active". You can only test this on sway or hyprland right now, since we need an IPC for workspace tracking and manipulation.

I haven't used tint2 myself, so any comments and corrections are welcome of course.

![20231018_07h57m46s_grim](https://github.com/LBCrion/sfwbar/assets/76477076/be4242a1-ae06-400e-bdd7-6130a9ff661c)

**Comment by lstrtstr** [comment]
Thank you so much!

> Each workspace has it's name followed by buttons for all windows on this workspace. Dragging windows into another workspace moves them to that workspace (you can drag either into a workspace label or any window button on that workspace).

(Unfortunately, I haven't had time to install sway and the latest git yet, sorry!)
Does this mean it works by dragging the _actual windows_ onto the bar, or by dragging the "tasks" within the bar?
I assume it's the latter, and that's exactly how tint2 does it: you drag the "tasks" from workspace bar to workspace bar within the taskbar. (If it does not work like that, adding that behavior would be nice.)

> I haven't used tint2 myself, so any comments and corrections are welcome of course.

The functionality is basically the same (see above), but the visual representation and the way space is handled are different.
Here's an example from tint2:
![image](https://github.com/LBCrion/sfwbar/assets/11430024/06689c54-cf37-44d3-aedf-c2518602ad6c)
The split bars each have a fixed width (so there might be some empty space, as in the example), their own edges and margins, and there are no workspace labels.

The way these things are handled differently in sfwbar _does_ make sense to me. From a perspective of "tint2 visuals," though, It would be nice to be able to customize them and configure whether
* the split bars have fixed or dynamic widths
* the split bars have separate edges and margins
* the workspace labels are shown

Anyway, thanks again for implementing this awesome and incredibly useful feature!

**Comment by LBCrion** [comment]
You do indeed drag the tasks within the taskbar. Dragging the actual windows would require a lot of cooperation from the compositor, so not something that would be easy to implement.

Making the workspaces equal width would be very easy (that's actually the default behavior, I had to work around it to make them unequal width!) I added two new CSS properties ``-FlowGrid-row-homogeneous`` and ``-FlowGrid-column-homogeneous`` to control this in the latest git.

Workspaces within the split bar have their own CSS nodes, so you can set edges and margins for them already, the CSS nodes are ``grid#taskbar_pager_normal`` and ``grid#taskbar_pager_active``

I added an option to control this in the latest git version. Same option as in all taskbars ``label = true`` to turn workspace names on, and ``labels = false`` to turn them off.

Here's how it looks with these options applied:
![20231021_18h33m54s_grim](https://github.com/LBCrion/sfwbar/assets/76477076/f629e608-11dc-4505-8bf6-2a95d476d7db)

**Comment by lstrtstr** [comment]
Awesome!
I don't think there's anything else to add.

If I encounter any bugs or weird behaviors in the future, I'll open another issue.
