### ISSUE TITLE
Feature request: minimize window

### ISSUE THREAD

**Issue by elgithubo** [LBCrion/sfwbar#130]
I would love to be able to minimize a window again by clicking on the active window in the window list.
I am used to this behavior from practically any window manager (and from Windows)m, so I always click and nothing happens.

I hope it is clear what I mean :)

**Comment by LBCrion** [comment]
@elgithubo, it's clear and it should be the default behavior of the taskbar in sfwbar. I just tried both the latest git and the beta13 on my machine and when I click on a focused window in the taskbar, the window is minimized.
What compositor are you using and do you have any actions set in the taskbar declaration in your config?

**Comment by elgithubo** [comment]
I am using labwc compositor.
[config.zip](https://github.com/LBCrion/sfwbar/files/13697312/config.zip)
I have attached my config.

Does that give you an idea already or shall I debug the issue?

**Comment by LBCrion** [comment]
This is interesting. I was able to reproduce this on labwc. It looks like when you click a taskbar button, labwc deactivates the window before sfwbar triggers the action and then activates it again. sfwbar doesn't minimize the window because it's not focused when the action is called.

@Consolatis, do you know by any chance if labwc unsets the window focus (foreign toplevel `active` state) when a layer shell window is clicked?

**Comment by Consolatis** [comment]
Hm.. we did refactor the focus handling a while ago. It might be possible that we overlooked something. Thanks for pointing this out. What version of labwc did you test, the master branch or the last 0.6.6 release?

**Comment by johanmalm** [comment]
We could probably fix this on `labwc` but interestingly I can re-produce it on `sway` since https://github.com/LBCrion/sfwbar/commits/113093f8642c56b9eabf153460aee11dfcb0d673

**Comment by LBCrion** [comment]
@johanmalm, this looks to be triggered by querying the keyboard modifiers. Sfwbar enables layer shell keyboard interactivity to query the modifiers. We need to run 3 gtk iteration for the modifier information to propagate and become available. During these iterations, sfwbar receives and processes a focus loss event (none of the toplevels gain focus, since layer shell windows are not listed among the foreign toplevels). Once sfwbar queried the modifiers, it switches keyboard interactivity off, but without additional gtk iterations between interactivity give-up and action invocation, sfwbar doesn't receive the toplevel focus event.

It takes 5 gtk iterations for sfwbar to receive and process  the toplevel focus event after giving up interactivity. The process of querying the modifiers is hacky in general. Sfwbar replies to gtk internals to behave consistently (i.e. the number of iterations to propagate these changes to remain constant). Unfortunately, the behavior of the layer shell `on demand` interactivity is too inconsistent among compositors, and can result in a de-facto locked session.

I've added this workaround to the latest git. @elgithubo, can you please check if the latest git version behaves as expected for you?

**Comment by Consolatis** [comment]
> Unfortunately, the behavior of the layer shell `on demand` interactivity is too inconsistent among compositors

I think both hyprland and sway fixed that specific issue and should now treat `ON_DEMAND` correctly (or only announce version 3 of the layershell protocol which doesn't support `ON_DEMAND`).
However, it wouldn't really help in this case anyway as the focus would still shift over to sfwbar on click.

We need some kind of protocol that causes the keyboard modifiers event to be sent to panels even if they don't currently have keyboard focus. This is also a requirement for a keyboard layout indicator (without hacky led-is-active workarounds).

> and can result in a de-facto locked session

For the `EXCLUSIVE` mode (and previously wrongly implemented `ON_DEMAND`): yes, that is a possibility (and also quite annoying). I've thought about allowing keybinds like `A-Tab` to reset the exclusive keyboard focus so the user is at least able to resume the session by killing the layershell client in some terminal.

**Comment by elgithubo** [comment]
@LBCrion I can confirm you workaround fixes my issue.
I can minimze an active windows by clicking on it in the window list and als the highlighting for the active window changes correctly.
Thanks a lot!

**Comment by johanmalm** [comment]
`sfwbar` works with patch https://github.com/labwc/labwc/pull/1342 (or the other way around depending on how one looks at this).

Why do you want the modifiers? For displaying keyboard layout?

See: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4496

Will attempt a protocol to broadcast modifiers to specific clients (such as panels) rather than all.

**Comment by LBCrion** [comment]
We query modifiers to support binding actions to Modifier+Click events.

**Comment by johanmalm** [comment]
I see. So, do you request keyboard-interactivity (on_demand) after receiving a pointer-press-event?

**Comment by LBCrion** [comment]
I actually request EXCLUSIVE mode for just long enough to query the
modifiers, then switch to NONE. The only reason I use EXCLUSIVE is due to
the erratic behavior of ON_DEMAND I observed on some compositors.

**Comment by elgithubo** [comment]
Since this is solved in beta14, I am closing the issue.
Please reopen if required.
