### ISSUE TITLE
sfwbar openbox 

### ISSUE THREAD

**Issue by WgpArch** [LBCrion/sfwbar#158]
Trying to get sfwbar test run in Arch Linux openbox 
[wgparch@archlinux sfwbar]$ env | grep WAYLAND
WAYLAND_DISPLAY=wayland-0
[wgparch@archlinux sfwbar]$ GDK_BACKEND=x11 sfwbar

(sfwbar:99498): Gdk-CRITICAL **: 09:23:12.093: gdk_wayland_display_get_wl_display: assertion 'GDK_IS_WAYLAND_DISPLAY (display)' failed

** (sfwbar:99498): ERROR **: 09:23:12.093: Can't get wayland display

Trace/breakpoint trap (core dumped)

**Comment by LBCrion** [comment]
Sfwbar has been written for wayland so far (or more specifically for
wlroots based compositors). Most of the architecture is now sufficiently
abstract,  that it wouldn't be hard to add x11 dock support instead of
wlr-layer-shell protocol and x11 window tree instead of
wlr-foreign-toplevel).

That said a lot of concepts in sfwbar are aligned with wayland (I.e. using
appid for icon lookups - X11 approach of an application supplying its icon
wouldn't map well to sfwbar internals).

In general,  I can take a stab at adding basic x11 support, but it probably
wouldn't work as well as in native x11 bars.

**Comment by WgpArch** [comment]
Thanks then I will use Sway as window manager and leave Openbox. The whole reason for my taskbar search is caused by tint2 disappearing.I will just simply replace Openbox with Sway and learn something new thanks again.

**Comment by Consolatis** [comment]
> Thanks then I will use Sway as window manager and leave Openbox. The whole reason for my taskbar search is caused by tint2 disappearing.I will just simply replace Openbox with Sway and learn something new thanks again.

Shameless self-plug: there is also https://github.com/labwc/labwc if you end up missing openbox.

**Comment by WgpArch** [comment]
Thanks will go have a look at it any idea why would tint2 just disappear and core dump? I even rebuilt my arch setup a week ago hoping it would solve the issue but it did not.

**Comment by Consolatis** [comment]
I don't have that much experience with tint2, I suggest using their bug tracker for that.

**Comment by salahoued** [comment]
@WgpArch , The lead  maintainer of tint2 [https://gitlab.com/o9000/tint2](url) has dropped support and ended tint2 and their latest version 17.0.2 is the one in arch repos (I think).

but there is someone who picked up the code in [https://gitlab.com/nick87720z/tint2/](url) you may want to try looking there.

**Comment by LBCrion** [comment]
Closing this, as the original question is answered I believe.
