### ISSUE TITLE
Nice to have: 'margin' from respective edges for window

### ISSUE THREAD

**Issue by 01micko** [LBCrion/sfwbar#159]
Since 0.5 `gtk-layer-shell` has supported margins:

```c
void gtk_layer_set_margin (GtkWindow *window, GtkLayerShellEdge edge, int margin_size);
```

With that we could have a _real_ `tint2` config that 'floats' a little off the edges. 

I'd imagine this could be part of the `SfwbarInit`; here's a pseudo config for the bar at top of screen:

```
function("SfwbarInit") {
  SetBarId "panel"
  SetLayer "panel", "bottom"
  SetMonitor "panel", "HDMI-A-1"
  SetExclusiveZone "panel", "35"
  SetTopMargin "panel", "5"
  SetLeftMargin "panel", "5"
  SetRightMargin "panel", "5"
}
```

**Comment by 01micko** [comment]
Maybe just one option is ok; `SetMargin`, and figure out if bar is up top, down bottom, left or right.

**Comment by LBCrion** [comment]
I added SetBarMargin to the git version, i.e. `SetBarMargin "10"` to set 10px margin on all sides. So far there is no way to control individual edges (but would be easy to add).

While we're on this topic, sfwbar currently has two different ways to configure widget properties. Directly in the layout (i.e. `icons = true`) and via `Set` actions, i.e. `SetBarSize` or `SetValue`. The later approach evolved as means to dynamically modify the layout before we had addressable widgets. We can now modify the layout using `Config` action, which is a lot more flexible than `Set`s. 

I wonder if it's worth moving bar property management to properties rather than continuing to use `Set` functions for these. (this can be a gradual process, i.e. add properties and deprecate the Set functions over time).

**Comment by 01micko** [comment]
Thanks. `SetBarMargin` works perfectly. My work around was to set the margin in `labwc/rc.xm` but that affects _all_ windows.

I think the `Config` idea is worth pursuing going forward.

**Comment by 01micko** [comment]
There seems a bug with the new `margin property`. `SetBarMargin "4px"` works fine with deprecation warning but `margin "4px"` does nothing, no error either.

**Comment by 01micko** [comment]
No, my bad, must go in layout
```
layout { 
  margin = 4 
}
```

sorry for noise
