### ISSUE TITLE
High cpu usage with  "-GtkWidget-max-width:" and "-GtkWidget-max-height:" 

### ISSUE THREAD

**Issue by knm100** [LBCrion/sfwbar#186]
After setting the  property "-GtkWidget-max-width:" and "-GtkWidget-max-height:" , the CPU have a high usage .
  it returns to normal after deleting "-GtkWidget-max-width:" and "-GtkWidget-max-height:" ,
button#module,
button#launcher,
button#showdesktop {
  padding: 0px 3px 0px 3px;
  border: none
  -GtkWidget-max-width: 18px;
  -GtkWidget-max-height: 18px; 
  -GtkWidget-valign: center;
}

**Comment by LBCrion** [comment]
Did you manage to fix this,  or do you still see high cpu utilisation when
using these css properties?

**Comment by knm100** [comment]
That would certainly not continue to use these.

**Comment by LBCrion** [comment]
We should keep this open until we have a proper fix for this.

**Comment by knm100** [comment]
I has to say that"-GtkWidget-max-width:" and "-GtkWidget-max-height:"  is very useful.   Simple, straightforward, powerful, effective

**Comment by knm100** [comment]
To add in more detail, my total CPU usage is around 56%, but both labwc and sfwbar have around 50 CPU usage in top.
I guess that SFWBAR communicates with labwc very frequently sothat CPU usage data changes too fast to be distinguished by my eyes.

**Comment by LBCrion** [comment]
Can you try adding the below to your ``#!CSS`` section:
``button { min-height: 0px; }`` and see if your ``-GtkWidget-max-height`` settings work after this?

**Comment by LBCrion** [comment]
Also, can I check what you're trying to do overall? ``-GtkWidget-max-height`` constrains the widget size but the widget would still respect min-height property. So if the widget (including it's children) has min-height greater than max-height, max-height won't have any effect.
In your example you're constraining ``button#module``, but this may be overridden by ``button#module image`` min-height.

**Comment by knm100** [comment]
> Can you try adding the below to your `#!CSS` section:
> `button { min-height: 0px; }` and see if your `-GtkWidget-max-height` settings work after this?

![swappy-20240516-073557](https://github.com/LBCrion/sfwbar/assets/166389780/7c7645e9-6236-4963-89e7-a81f788c76d4)
my setting  is as following:
button#module,
button#launcher,
button#showdesktop,
button#startmenu {
  padding: 0px 3px 0px 3px;
  border: none;     
  min-width: 0px;  /* Added with -GtkWidget-max-height/width */
  min-height: 0px; /* Added with -GtkWidget-max-height/width */
}

button#startmenu {      
  border: 1px solid;   /*added，In order to see if the settings take effect here*/
  border-color: green;  /*added，In order to see if the settings take effect here*/
  border-radius: 4px;  /*added，In order to see if the settings take effect here*/
  -GtkWidget-max-height: 10px;/* Added  */
  -GtkWidget-max-width: 10px; /* Added  */
}  

button#startmenu image {
  /* min-width: 18px;
  min-height: 18px;  */
  -GtkWidget-max-height: 10px; /* Added  */
  -GtkWidget-max-width: 10px;  /* Added  */
  -gtk-icon-effect: dim;
  padding: 1px;
}

**Comment by LBCrion** [comment]
Ok, image size specifications are as following. Image size is a square with size of ``Min(min-height, min-width)``. If min-height or min-width are not specified, they are set to a default size. This was 16px, I dropped it to 2px now. If the image has hexpand and/or vexpand set to true, it can grow from the minimum size if there is a space available.

``-GtkWidget-max-width/height`` will constrain an image if it's growing due to ``hexpand/vexpand``, but it won't shrink it smaller than ``min-height/width``. Shrinking it beyond min sizes can result in a merry game of resizing the image back and forth (which is what likely caused the high CPU usage).

So, in your example, since image has no min-width/height, it got the default of 16px, on top of that 1px of padding was added (so we're up to 20px total) and 1px of border for the button. Since the button border is rounded, it may add some extra space to accommodate a square image in a rounded button. Since the minimum required size is now up to 20px+, max-height argument doesn't have any effect.
