### ISSUE TITLE
"css" widget property apparently can't be an expression that evaluates to a string

### ISSUE THREAD

**Issue by jjramsey** [LBCrion/sfwbar#201]
This works as a widget property:
```
css = "* { -GtkWidget-direction: right; }"
```
This does not:
```
css = "* { -GtkWidget-direction: " + "right" + "; }"
```

If the latter worked, then the string `"right"` could be replaced by a string variable dependent on, say, `BarDir()`. Instead, I get errors like this:

```
(sfwbar:1980): Gtk-WARNING **: 07:47:44.456: Theme parsing error: <data>:1:26: Expected a property value

(sfwbar:1980): Gtk-WARNING **: 07:47:44.456: Theme parsing error: <data>:1:26: expected '}' after declarations
```
and the error message, "Invalid property in a widget declaration" preceded by the line number where the errant `css` property occurs.

Apparently, the `css` property can only be a string.

**Comment by LBCrion** [comment]
This is deliberate. CSS property creates a new CSS provider and attaches it
to the widgets style context. In order to be able to mirror the widget
correctly, it also maintains the list of all the CSS strings that have been
specified via css property already. The implications of this that the
program consumes memory every time a css property is specifies. If we allow
expressions to be used in the css property, it will almost certainly leak
memory by creating a multitude of css provider objects.
This is the reason I limited the use of expressions to the style property
with all the state specific variations specified in the main stylesheet.
It's possible in theory to allow expressions in the css property, but in
this case we would need to only allow a single css property definition per
widget.

**Comment by jjramsey** [comment]
In that case, you should clearly document this, because otherwise, it's very unexpected behavior.
