### ISSUE TITLE
The notifications center should be closed when the focus is not on it.

### ISSUE THREAD

**Issue by knm100** [LBCrion/sfwbar#238]
It would be inconvenient if needed to click on the icon on the panel for closing every time

**Comment by LBCrion** [comment]
You can add:
  Config "PopUp 'XNotificationWindow' { autoclose = true; }"
to Function("SfwBarInit") in your config

**Comment by knm100** [comment]
thanks,  maybe this should be  defalut .

**Comment by LBCrion** [comment]
The commented code is an example applicable to pulse audio module, you need
to add a new line with the correct popup ID (see my previous post for the
correct ID).

I don't add autoclose by default in the config because autoclose requires a
focus grab and it's not handled gracefully on all compositors.

**Comment by knm100** [comment]
Thank you very much!  it is working now.
