### ISSUE TITLE
Open window missing icon and application name

### ISSUE THREAD

**Issue by wastlnd** [LBCrion/sfwbar#259]
Hi, I am using the Pale Moon web browser, but the window tab just has a generic sfwbar icon and the "Navigator' name. I have checked the app_id and indeed it's "Navigator", the . desktop file exists too.

**Comment by LBCrion** [comment]
Can you post the name and contents of the .desktop file please?

**Comment by wastlnd** [comment]
Sure, the desktop file is palemoon.desktop, that's the content:
https://aur.archlinux.org/cgit/aur.git/tree/palemoon.desktop?h=palemoon-bin

**Comment by 01micko** [comment]
> Also, the PNG icon does show up in the left corner menu app list.

Do you mean the application menu? (I'm thinking so)

**Comment by wastlnd** [comment]
Yes, the issue is only about the open tab at the bottom.

**Comment by 01micko** [comment]
I use Vivaldi browser and it had a problems a couple of years ago. There is a workaround for `sfwbar` using :
```
MapAppId ".*Vivaldi$", "vivaldi"
``` 

In the toplevel of the main sfwbar.config. See [here](https://github.com/01micko/sfwbar-configs/blob/legacy/configs/sfwbar/sfwbar.config) (Don't touch that config otherwise, it's old! Many things have changed since then)

If you have `$HOME/.config/sfwabar.config` try adding that before the `layout` section obviously replacing the 'Vivaldi' with whatever Pale moon says in the labwc `alt-tab` OSD and the second part is the icon. If you don't have a user config copy the one from `/usr/share/sfwbar/sfwbar.config` to `$HOME/.config/sfwabar.config` and start editing :smile: 

From sfwbar/sfwbar.rst (man page)

> Miscellaneous
> If the icon is missing for a specific program in the taskbar or switcher, it is likely due to an missing icon or application not setting app_id correctly. You can check app_id's of running programs by running **sfwbar -d -g app_id**. if app_id is present, you need to add an icon with the appropriate name to your icon theme. If it's blank, you can try mapping it from the program's title (please note that the title may change during runtime, so matching it can be tricky). Mapping is supported via top-level MapAppId keyword. I.e.

> `MapAppId app_id, pattern`

I highlighted the `sfwbar -d -g app_id` part.

This _could_ tell us if it's an sfwbar/labwc problem or a Pale Moon problem (re https://github.com/labwc/labwc/issues/2299)

Good luck!

**Comment by wastlnd** [comment]
Thanks for the help guys! 
sfwbar -d -g app_id returns 'Pale Moon's
The package installs icons in /usr/share/icons/hicolor/{16x16,32x32,48x48,138x128}/apps/palemoon.png.

**Comment by 01micko** [comment]
> What are the names of the icons palemoon installs? Does it install both symbolic and regular icons?

AFAIK the arch `PKGBUILD` just installs `palemoon.png`, ref: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=palemoon-bin#n46

**Comment by LBCrion** [comment]
Can you please post the output of `sfwbar -d -g app_id`? It looks like there is an issue linking the app_id to the desktop file, but reading the above, I think it should be linking via the `Name=` property in the desktop file.

For the "Navigator" as a title, this is what pale moon seems to be supplying. We don't mangle the titles normally.

**Comment by wastlnd** [comment]
The output is 'Navigator' though in the palemoon.desktop file I read `Name=Pale Moon`

**Comment by LBCrion** [comment]
Is "Navigator" output for an app id or for the title?

**Comment by wastlnd** [comment]
It's for app_id, the second output is the title of the page that I opened

**Comment by Consolatis** [comment]
You can just add `StartupWMClass=Navigator` somewhere in the `[Desktop Entry]` section of palemoon.desktop file. It should fix it for both, labwc and sfwbar. Its an issue in the .desktop file of palemoon.
