### ISSUE TITLE
sfwbar-git-r1686.bf76d13 - svg problem

### ISSUE THREAD

**Issue by sfs-pra** [LBCrion/sfwbar#282]
https://github.com/01micko/sfwbar-configs/blob/main/configs/sfwbar/other/temp.widget
No icon is formed. Numbers are displayed normally
Everything worked in the sfwbar-git-r1622.64b65ff version.

**Comment by LBCrion** [comment]
This is because "define" hasn't been ported to the new vm based approach
yet. This would be  done for compatibility reasons only. With the new vm,
we don't really need "define" and can use "set" instead, since the
performance penalty the later used to incur is no longer there.

**Comment by sfs-pra** [comment]
Replacing "define" -> "set" did not solve the problem

**Comment by LBCrion** [comment]
At this point,  you can't just replace Define with Set due to the
difference in type casting. Define use straight up substitution,  so the
type is inferred from the expression. The type result of Set is explicitly
specified through the variable name. I.e. $string or numeric.val.
Looking at the file you're using,  all defines return strings,  so if you
replace define with set, you'll need to prefix variable names with $. I.e
value = $svg

You'll need to do this for every occurrence of a variable where you replace
define with set.

**Comment by LBCrion** [comment]
It may be easier to wait until I add define to the new parser.

**Comment by sfs-pra** [comment]
value = $svg - solved the problem !

The alsa-module.widget battery-svg.widget battery.widget bluez-popup.widget wifi.widget
 is also “define”, but they work as before.

**Comment by LBCrion** [comment]
'Define' should work with the new VM now. And in the process of
implementing it, I uncovered a nasty design flaw in the new VM, which is
now fixed, so this bug report saved me a lot of time down the road :)

**Comment by sfs-pra** [comment]
From the documentation, the difference between “set” and “define” is not very clear.
With “define” it was possible to use the same variable names in different widgets.
With “set” I had to rename

**Comment by LBCrion** [comment]
You should be able to use the same variable in various widgets with set. If
you find a config where it isn't working, can you please send me the
config, so I can check what's causing a bug?

The difference between defined and set is that define literally substitutes
the value in the config, while Set creates a variable that get calculated
when needed.

I.e.

Define a = b+c
value = a+d

will compile to value = b+c+d

Where's

Set = a = b+c
value = a+d

Would compile to a+d, where a would be calculated as b+c.

This used to be important because computing b+c in between required
initializing a parser and parsing expression b+c. This was computationally
intensive. Now all expressions are compiled to bytecode and evaluated in a
vm, so there should be no reason to use define over set.
