### ISSUE TITLE
Migration to new function api

### ISSUE THREAD

**Issue by sfs-pra** [LBCrion/sfwbar#283]
In recent Commits there is a lot about “migration to new function api”. Tell more about what improvements to expect and when the transition will be over

**Comment by LBCrion** [comment]
This is work associated with https://github.com/LBCrion/sfwbar/discussions/257 . Historically, sfwbar had expression functions (used to query data about state of the system) and actions (which could influence the state of the system). The two were completely separate and user defined "functions" were really just lists of actions strung together. 

The new VM based approach would merge the expression functions and actions and will eventually allow for more sophisticated user defined functions (i.e. functions should gain some flow control capabilities (if, the, for, etc.) and can return a value, so that you can write actual user defined functions for data manipulations and avoid the mess we have in widgets like cal.widget).

As part of this migration all internal implementations of the standard function and action libraries had to be migrated to the new API. This should now be complete and I can start deprecating the old format and implement the new functionality.

**Comment by sfs-pra** [comment]
sfwbar-git r1723.c609476 - is the migration completely complete?

**Comment by LBCrion** [comment]
The migration is complete as far as rewiring the native functions to the
new api is concerns.  All native functions are now using the new api and
the compatibility layer had been removed.

Now comes the fun part of enabling the new functionality (which was the
purpose of the vm implementation). We already have flow control with
if/then, loops with while and local variables.  Next come user defined
functions that can accept and return parameters.

**Comment by sfs-pra** [comment]
Where can I read about using if/then and stuff like that ?

**Comment by LBCrion** [comment]
I need to finish implementing it before I document (things are still changing quite rapidly right now). But here's an example of a config snippet to show what you can do:
```
Function valget(n) {
  return n*2+1;
}

Function AddStuff() {
  Var i;

  i = valget(2)
  While i > 0 {
    if(i % 2 = 1)
      config "layout { label { value =' " + Str(i) + " ' } }"
    i = i - 1
  }
}

Function("SfwbarInit") {
  AddStuff()
}
```
