### ISSUE TITLE
Usage widget no longer updates at run time

### ISSUE THREAD

**Issue by Vimux** [LBCrion/sfwbar#70]
Usage widget (`usage.widget`) no longer updates at run time, only at first startup (?). Commit 15d3d628d87a8d8527aee28e9671e20e0db78a27 seems to be the cause. It affects other widgets as well.

**Program version:**

* sfwbar [commit 735a1c62c8368d3a41253cd74679e6f0494c1f60]

**Comment by LBCrion** [comment]
This looks like over-zealous optimization of scan variables that got introduced while optimizing itermediate vars. Can you please check if the latest git version fixes the issue for you?

**Comment by Vimux** [comment]
It works, but something wrong with the tooltips. Now, `test\ntest` does not create line break. Up to this point, I thought that these are related problems, but it looks like that they are different.

**Comment by LBCrion** [comment]
I just tried adding tooltip = "test\ntest" and got a line break in a tooltip. This is with the latest git version. Could you post the config causing this, so I can debug it? The commit above does change behaviour of escaped characters in expressions, so I very much want to make sure I fix any breakage it may have caused.

**Comment by Vimux** [comment]
`tooltip = 'test\ntest\test'` != `tooltip = "test\ntest\ntest"`

My fault. It didn't matter before. Case closed.

**Comment by LBCrion** [comment]
This is interesting. It appears that glib lexical scanner handles escape sequences differently in single and double quoted strings. We got an equivalent behavior previously because sfwbar config parser internally converts single quoted strings to double quoted strings. With the new expression string parser code, the escape sequences are preserved (i.e. \n is converted to \\n). For double quoted strings this works correctly (i.e. parser would only encounter \n if the original string was "test\\ntest"), but for single quoted strings we get a different behavior, i.e. 'test\ntest' is converted to "test\\ntest". This is why you now need to use double quoted strings in the config if you want to use escape sequences.

**Comment by 01micko** [comment]
This is consistent with shell utilities `echo`, `printf` so not a problem,

**Comment by LBCrion** [comment]
I think I knew this once upon a time :P . Since this is a reasonably
standard behaviour, I'll leave this as it is now, rather than trying to
recreate the old behaviour,  which was a result of a bug.
