### ISSUE TITLE
Current keyboard layout widget?

### ISSUE THREAD

**Issue by gerdamit** [LBCrion/sfwbar#77]
Hello. I tried sfwbar not too long ago, I liked it very much, special thanks for SVG, no need to bother with icon fonts!

Any idea how to display current keyboard layout?

I'm using Sway, tried a few options , but they all failed. The documentation not very generous with examples for SwayCmd, SwayWinCmd, SwayClient, ExecClient, SocketClient. The standard configs either don't use them at all, or do so in a non-obvious way for me 😫

**Comment by LBCrion** [comment]
I do need some examples of using SwayClient, and this is a good use for the functionality. Of course looking at the source, I found an error in the name of sway ipc events in SwayClient. This is fixed in current git. A basic example would look like this:

sway-lang.widget:
```
scanner {
  SwayClient("") {
    SwayXkbLayout = Json(".input.input.xkb_active_layout_name")
  }
}

Function("sway_lang_init") {
  SwayCmd "input type:keyboard xkb_switch_layout next"
  SwayCmd "input type:keyboard xkb_switch_layout prev"
}

layout {
  label {
    action[0] = Function "sway_lang_init"
    value = $SwayXkbLayout
    trigger = "sway"
  }
}
```
This works as following, the widget connects to SwayClient scanner source and listens to input events, when an event is received it stores XkbLayout in variable $SwayXkbLayout, which the widget displays.
The init function, toggles the xkb layout back and forth to populate the initial state of the variable.
The widget updates on ``sway`` trigger to avoid excessive updates.

The downside of this is that the XkbLayout names provided by sway are rather verbose, if you know the names of your layouts, you can map them to abbreviations:

```
value = Map($SwayXkbLayout,"English (US)","EN","Modern Elbonian","EL","Huh?")
```
This of course isn't great since you need to edit the widget every time you change available layouts. The cleaner way would be to expose xkb layout tables. I'll try to add a module to support this.

**Comment by gerdamit** [comment]
Great, it works. Thanks for the quick response and this example.

Personally, I don't add new keyboard layouts that often, even long-name solution is fine for me 😄 The map solution would require manipulation only once, so no problem. I'm closing this for now, thanks again.

**Comment by LBCrion** [comment]
I added an xkbmap module to do automatic mapping in the latest git version. Using it, all layouts should be mapped to abbreviation automatically. The widget looks like this:

```
module("xkbmap")

scanner {
  SwayClient("") {
    SwayXkbLayout = Json(".input.input.xkb_active_layout_name")
  }
}

Function("sway_lang_init") {
  SwayCmd "input type:keyboard xkb_switch_layout next"
  SwayCmd "input type:keyboard xkb_switch_layout prev"
}

layout {
  label {
    action[0] = Function "sway_lang_init"
    style = If(Ident(SwayXkbLayout) & $SwayXkbLayout!="","sway_lang","hidden")
    value = XkbMap($SwayXkbLayout,"description","brief")
    trigger = "sway"
  }
}
```
