### ISSUE TITLE
Weird tray icon (zoom) behavior

### ISSUE THREAD

**Issue by keshto** [LBCrion/sfwbar#78]
```
◗ labwc -v
labwc 0.6.1-83-g50a6c78

sfwbar -- master as of 3 days ago
```

I don't have that many tray icons. However, Zoom (the application) tray icon on right click popups a window with a menu (see attached picture) in the middle of the screen. On left click popups same menu correctly.

Desired behavior (do what waybar does):
- left click shows/focus client
- right click shows menu

![image](https://user-images.githubusercontent.com/766237/227077813-46e6113e-3d78-4e46-81a9-84e61fc31d49.png)

**Comment by LBCrion** [comment]
Thank you for testing this. Can you please check if middle click gets you the menu you expect to see under either button? I suspect we may be running into the flipside of https://bugs.launchpad.net/ubuntu/+source/libappindicator/+bug/1910521

**Comment by keshto** [comment]
Middle click does nothing

**Comment by keshto** [comment]
`network-manager-gnome/testing,unstable,now 1.30.0-2 amd64 [installed]` so looks like same version. On waybar I don't get the menu in the screenshot above but instead the one i currently get on right click in sfwbar (for both left and right click). In JWM I get the menu in screenshot on right click.

**Comment by keshto** [comment]
This "left click doing nothing right click showing what left click should be" behavior is also happending for `package-update-indicator/testing,unstable,now 8-2 amd64 [installed]` so don't think it is a nm-applet thing. Maybe libindicator?

**Comment by LBCrion** [comment]
Ok, so the only difference from waybar is the left click? waybar pops up the same menu as on right click and sfwbar does nothing?

JWM provides a freedesktop tray I believe. That's an X11 based protocol and won't work natively on wayland. The only way to replicate this is to use xembedsniproxy and Xwayland (this will produce ugly looking icons and menu's popping up in the center of the screen).

**Comment by keshto** [comment]
> Ok, so the only difference from waybar is the left click? waybar pops up the same menu as on right click and sfwbar does nothing?

Correct.

>JWM provides a freedesktop tray I believe. That's an X11 based protocol and won't work natively on wayland. The only way to replicate this is to use xembedsniproxy and Xwayland (this will produce ugly looking icons and menu's popping up in the center of the screen).

Don't think that is the right solution. You did mention that you saw (attached) on right click? If so on left click you should see something else and if that is the case you have correct behavior.
![image](https://user-images.githubusercontent.com/766237/227375556-219c3bbd-32c6-435a-8a8d-92ff774a49e2.png)

**Comment by LBCrion** [comment]
I see the above (or a very similar menu at least) on both left and right click in waybar.

The left click behaviour looks like a difference between the StatusNotifierIcon spec and the libappindicator implementation of the spec. Per spec, the tray (StatusNotifierHost) should send Activate event on left click, unless application sets ItemIsMenu property to true, in which case ContextMenu event is sent or menu is popped up. libappindicator seems to popup a menu on left click regardless of ItemIsMenu setting (which makes sense since bug report I linked earlier mentions that libappindicator doesn't support the Activate event).

**Comment by keshto** [comment]
In waybar the left and right open the same menu which is not the one above. The one above is the result of the right click on x11 (I haven't tried xfce panel or something similiar). The left click opens up a list of wireless networks where as the right should open the above. The update app indicator has same effect with sfwbar (left and right click both bring up the normally left click only menu and dont have a way to bring up the normal right click menu)

**Comment by keshto** [comment]
![image](https://user-images.githubusercontent.com/766237/227403936-ffe2267d-312d-4d35-90f2-9c51261ed456.png)
notice how this menu is different then the one above. This one should be the left click and the one above the right click

**Comment by LBCrion** [comment]
Ok, it looks like with the X tray (freedesktop tray) nm-applet uses 2 menu's, one for connections and one for settings. With StatusNotifierItem tray, it combines them into a single menu. This is because SNI only supports one menu (second menu can be implemented by the applet itself, but it can't be positioned gracefully). So in wayland we'll only have the one menu version.

This still leaves the question of left mouse button click. I'm not too keen to emulate the libappindicator behaviour, as it goes against the SNI spec and would break applets that actually use Activate event. It would be possible to add a tray property to allow switching the behaviour between SNI spec and libappindicator implementation.

**Comment by Consolatis** [comment]
That sounds like a good approach. Defaulting to SNI spec behavior seems like the best thing to do.

**Comment by keshto** [comment]
Is waybar not following the SNI spec because it uses left and right for the same action for nm-applet which is more intuitive imo. Maybe follow SNI, if there is no left click action then invoke right click?

I will report shortly back about different indicator.

**Comment by LBCrion** [comment]
Do you see the two menus in jwm? If so,  I would expect this is using the
Freedesktop tray as well.

**Comment by keshto** [comment]
Tested on plasma (wayland) and it looks like tray icons in general are just lame for wayland. I think if we do as above ie. follow SNI spec and set rightclick action to left click (if an action does not exist) in other words mimic waybar's functionality we should be good.

**Comment by LBCrion** [comment]
Ok, I looked at how Waybar handles this and it looks like it just assumes that ItemIsMenu set tot TRUE unless it's set as FALSE. Since libappindicator tray items don't have ItemIsMenu property defined, it handles left click as a menu popup. I changed this property to be TRUE by default and we should now have the same behaviour as with waybar.

**Comment by keshto** [comment]
Tested and it all cherry! Thanks again!
