### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by keshto** [LBCrion/sfwbar#80]
```
◗ sfwbar 
Segmentation fault
```
with GDB
```
Starting program: /usr/local/bin/sfwbar 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff5bff6c0 (LWP 1778)]
[New Thread 0x7ffff53fe6c0 (LWP 1779)]
[New Thread 0x7ffff4bfd6c0 (LWP 1780)]
[New Thread 0x7fffe7fff6c0 (LWP 1781)]
[New Thread 0x7fffe55ff6c0 (LWP 1782)]
[New Thread 0x7fffe4dfe6c0 (LWP 1783)]
[New Thread 0x7fffd7fff6c0 (LWP 1786)]

Thread 1 "sfwbar" received signal SIGSEGV, Segmentation fault.
net_update_ifaddrs () at ../modules/network.c:76
76	    switch(iter->ifa_addr->sa_family)
```

**Comment by keshto** [comment]
Note this only happens when using default config ie. no config in ~/.config/*

**Comment by LBCrion** [comment]
Can you try with the current git please? It should hopefully be fixed in the current version.

**Comment by LBCrion** [comment]
The silent failure is somewhat intentional, but can probably be handled more gracefully. sfwbar could in theory be running with no layouts and function as a task switcher or a window placer. That said, if there are no layouts, so switcher and no placer defined, we should probably bail with an error.

**Comment by LBCrion** [comment]
I added the above behaviour in the latest git version.

**Comment by keshto** [comment]
Awesome!
